// Cell-background transparency for the toolbar's opacity slider.
//
// The slider used to fade only the panel tint that sits *behind* the grid
// (--term-alpha on .term-wrapper). Every cell that carries its own SGR
// background — tmux's status bar, a reverse-video prompt line, a TUI's
// selected row — kept painting fully opaque on top of it, so at low panel
// opacity those filled bands were the one thing still hiding the picture
// behind the window. Text must NOT fade with them: a translucent glyph over
// live video is unreadable, and the whole point of a see-through shell is
// reading the shell while the picture plays.
//
// xterm's DOM renderer colours cell backgrounds two ways, and both end up
// pointing at one CSS variable (--term-cell-alpha, set on .term-wrapper right
// next to --term-alpha) so dragging the slider only re-resolves a variable and
// never forces a re-render:
//   * indexed colours (SGR 40-47/100-107, 48;5;N) via `.xterm-bg-<N>` classes
//     from xterm's own injected stylesheet — restated here in rgba() form and
//     won on !important (see buildCellBackgroundCss);
//   * 24-bit colours (48;2;r;g;b) via an inline `background-color:#rrggbb` that
//     no stylesheet can re-alpha without also losing the hue — rewritten as the
//     row factory produces it (see cellBackgroundStyle + its caller in
//     terminal.js).
// Foregrounds are deliberately untouched in both paths.
//
// DOM-free on purpose so tests/cell-bg.test.mjs can cover the colour maths.

export const CELL_ALPHA_VAR = "--term-cell-alpha";
// xterm's sentinel palette slot for "inverse video with the default colours":
// the fg/bg swap paints the cell in the theme's foreground. Same 257 as
// xterm's INVERTED_DEFAULT_COLOR, restated so we don't import a private const.
export const INVERTED_DEFAULT_COLOR = 257;

// xterm ITheme keys for palette slots 0-15, in index order.
const ANSI_KEYS = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
];

// xterm's DEFAULT_ANSI_COLORS for slots 0-15. Only reached when a theme leaves
// a slot unset — xterm would fall back to exactly these, and our rgba() rule
// has to restate the same colour or it would recolour the cell, not just
// re-alpha it.
const DEFAULT_ANSI = [
  "#2e3436", "#cc0000", "#4e9a06", "#c4a000",
  "#3465a4", "#75507b", "#06989a", "#d3d7cf",
  "#555753", "#ef2929", "#8ae234", "#fce94f",
  "#729fcf", "#ad7fa8", "#34e2e2", "#eeeeec",
];

const CUBE_LEVELS = [0, 95, 135, 175, 215, 255];

// Slots 16-255 are generated by xterm itself and never come from the theme:
// a 6x6x6 colour cube followed by 24 greys. Mirrors ThemeService's own loop.
export function indexedAnsiRgb(index) {
  if (index >= 16 && index < 232) {
    const i = index - 16;
    return [
      CUBE_LEVELS[((i / 36) % 6) | 0],
      CUBE_LEVELS[((i / 6) % 6) | 0],
      CUBE_LEVELS[i % 6],
    ];
  }
  if (index >= 232 && index < 256) {
    const v = 8 + 10 * (index - 232);
    return [v, v, v];
  }
  return null;
}

// Accepts the CSS colour forms an xterm ITheme may use — #rgb, #rrggbb,
// #rrggbbaa, rgb()/rgba() — and drops any alpha the theme carried: alpha now
// comes from the slider variable. Returns null for anything unparseable so
// callers can leave xterm's own rule in place rather than paint a wrong colour.
export function parseColorToRgb(value) {
  const raw = String(value == null ? "" : value).trim();
  const hex = /^#([0-9a-f]{3,8})$/i.exec(raw);
  if (hex) {
    const digits = hex[1];
    if (digits.length === 3 || digits.length === 4) {
      return [0, 1, 2].map((i) => parseInt(digits[i] + digits[i], 16));
    }
    if (digits.length === 6 || digits.length === 8) {
      return [0, 2, 4].map((i) => parseInt(digits.slice(i, i + 2), 16));
    }
    return null;
  }
  const fn = /^rgba?\(([^)]*)\)$/i.exec(raw);
  if (fn) {
    const parts = fn[1].split(/[,/\s]+/).filter((p) => p.length);
    if (parts.length < 3) return null;
    const channels = parts.slice(0, 3).map((part) => {
      const pct = /^([-+]?[0-9.]+)%$/.exec(part);
      const n = pct ? (Number(pct[1]) / 100) * 255 : Number(part);
      if (!Number.isFinite(n)) return null;
      return Math.max(0, Math.min(255, Math.round(n)));
    });
    return channels.some((c) => c === null) ? null : channels;
  }
  return null;
}

// Filled cell backgrounds track the panel's alpha 1:1, so "slider left" means
// the same thing everywhere and 100% stays exactly as solid as it has always
// been. The floor is what keeps them readable: a filled band is typically where
// the foreground goes dark-on-light, and fading its background to the panel's
// 20% would leave dark glyphs standing on bright video.
export const CELL_ALPHA_FLOOR = 0.3;

export function cellAlphaFor(percent) {
  const alpha = Number(percent) / 100;
  // A non-finite percent means the caller lost its state; full opacity is the
  // safe answer there, not a floor that would dim the shell for no reason.
  if (!Number.isFinite(alpha)) return 1;
  return Math.min(1, Math.max(CELL_ALPHA_FLOOR, alpha));
}

export function rgbaWithAlphaVar([r, g, b], varName = CELL_ALPHA_VAR) {
  return `rgba(${r}, ${g}, ${b}, var(${varName}))`;
}

// Whether a declaration the row factory is about to write is a cell
// background. Used for two things: re-alphaing it below, and marking the span
// so the Chameleon ink map can leave it alone — a glyph on a filled cell is
// not sitting on the picture, so it must not be painted from the picture's
// colours (see the note on --chameleon-flat-ink in styles.css).
export function isCellBackgroundStyle(style) {
  const raw = String(style == null ? "" : style);
  const colon = raw.indexOf(":");
  if (colon < 0) return false;
  return raw.slice(0, colon).trim().toLowerCase() === "background-color";
}

// Marks a span carrying an inline cell background. An attribute, not a class:
// the row factory assigns `element.className` wholesale *after* the styles are
// written, so any class added here would be dropped again the moment the cell
// also happens to be bold, dim or part of a link.
export const INLINE_CELL_BG_ATTR = "data-cell-bg";

// Rewrites the row factory's inline `background-color:#rrggbb` into the same
// colour at slider alpha. Any other declaration — notably the sibling
// `color:#rrggbb` for 24-bit *text* and the letter-spacing style — is returned
// untouched, which is what keeps glyphs opaque on this path.
export function cellBackgroundStyle(style, varName = CELL_ALPHA_VAR) {
  const raw = String(style == null ? "" : style);
  const colon = raw.indexOf(":");
  if (colon < 0) return style;
  if (raw.slice(0, colon).trim().toLowerCase() !== "background-color") return style;
  const rgb = parseColorToRgb(raw.slice(colon + 1).replace(/;\s*$/, ""));
  if (!rgb) return style;
  return `background-color:${rgbaWithAlphaVar(rgb, varName)}`;
}

// The stylesheet that re-alphas every indexed cell background. !important is
// load-bearing twice over: xterm re-injects its own `.xterm-bg-<N>` rules into
// the same document on every theme change (so document order can't be relied
// on), and the same declarations also have to out-rank the inline styles that
// the selection path writes.
export function buildCellBackgroundCss(palette, options = {}) {
  const scope = options.scope || ".term-wrapper";
  const varName = options.varName || CELL_ALPHA_VAR;
  const theme = palette || {};
  const rules = [];
  const push = (slot, color) => {
    const rgb = parseColorToRgb(color);
    if (!rgb) return;
    rules.push(
      `${scope} .xterm-bg-${slot}{background-color:${rgbaWithAlphaVar(rgb, varName)}!important}`,
    );
  };
  ANSI_KEYS.forEach((key, index) => {
    push(index, theme[key] || DEFAULT_ANSI[index]);
  });
  for (let index = 16; index < 256; index++) {
    push(index, `#${indexedAnsiRgb(index)
      .map((c) => c.toString(16).padStart(2, "0"))
      .join("")}`);
  }
  // Inverse video with default colours paints the cell in the foreground
  // colour; the glyph is painted in the background colour by xterm's
  // `.xterm-fg-257` rule, which we leave alone.
  push(INVERTED_DEFAULT_COLOR, theme.foreground || "#ffffff");
  return rules.join("\n");
}
